spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gamebase
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080